---
title: "p8105_mtp_jy3269"
author: "Jingyi Yao"
date: "`r Sys.Date()`"
output: github_document
---

```{r,warning=FALSE, message=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(readxl)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Problem 1 -- Data

### I. Weight data

#### Issue 1: incorrect column names  
```{r}
raw_data_weight <- read_excel("./data/dogweights_07may2022.xlsx",range = "B1:F363") 

weight = raw_data_weight      # preserve the raw data for later comparison

colnames(weight) = weight[1,] # change column names

weight <- weight[-1,]         # omit the first row which is the column name

weight

```


#### Issue 2: separate weight observations in 2 units for the 3 dogs 

```{r}
weight <- weight %>% 
  separate(Raisin, c("Raisin (Lbs)","Raisin (Oz)"), sep = " ", convert = TRUE) %>% 
  separate(Simone, c("Simone (Lbs)","Simone (Oz)"), sep = " ", convert = TRUE) %>% 
  separate(Gagne, c("Gagne (Lbs)","Gagne (Oz)"), sep = " ", convert = TRUE) %>% 
  separate(std, c("std (Lbs)","std (Oz)"), sep = " ", convert = TRUE) %>% 
  rename(Date = DATE) %>% 
  janitor::clean_names()

weight
  
```


#### Issue 3: messy data format shown in R

```{r}
unique(weight$date)                # find outliers in date

which(weight$date == "s")          # locate the outlier

weight <- weight %>% 
  mutate(date = as.numeric(date))  # transform data type and the “s” will be NA

# use the middle day between the 76th and 78th day.
weight$date[is.na(weight$date)] <- round(((weight$date)[78] + (weight$date)[76])/2)


# change the numbers into date format
weight <- weight %>% 
  mutate(date = as.Date(weight$date, origin = "1899-12-30"))

# another data set to store the date in a separated way
weight_1 <- weight %>%  
  separate(date, into = c("Year","Month","Day"),sep = "-") %>% 
  mutate(Month = month.abb[as.numeric(Month)])

write_csv(weight,file = "data/weight.csv")
```


#### 4. tidy the data

```{r}
weight_2 <- weight %>% 
  pivot_longer(                          
    raisin_lbs:std_oz,
    names_to = "dog", 
    values_to = "weight") %>% 
  separate(
    dog, into = c("dog","unit"),sep ="_"
  )

weight_2


```



### II. Notes

```{r}
raw_data_note <- read_excel("./data/dogweights_07may2022.xlsx",range = "G2:G363") 

date <- weight[,1:3]

note <- cbind(date,raw_data_note)

colnames(note)[4] <- "Notes"

write_csv(note,file = "data/note.csv")
```



## Problem 2 : EDA

#### 1. number of unique date
```{r}
num_unique_date <- length(unique(weight$Date))

```


#### 2. number of observations for each dog
```{r}
weight_2 %>% 
  group_by(dog,unit) %>% 
  summarize(
    avg_weight = mean(weight,na.rm = T),
    sd_weight = sd(weight,na.rm = T),
    num_obs = n()
  ) %>% 
  knitr :: kable()


```




